---
- name: Update package cache
  hosts: all
  become: true
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

- name: Configure admin
  hosts: admin
  become: true
  tags: admin
  roles:
    - users
    - common
    - admin

- name: Configure dev
  hosts: dev
  become: true
  tags: dev
  roles:
    - users
    - common

- name: Configure dns
  hosts: dns
  become: true
  tags: dns
  roles:
    - users
    - common
    - dns

- name: Configure media
  hosts: media
  become: true
  tags: media
  roles:
    - users
    - common
    - media

- name: Configure servers
  hosts: servers
  become: true
  tags: servers
  roles:
    - users
    - common
    - kvm
    - terraform
