---
- name: Update package cache
  hosts: all
  become: true
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

- name: Configure all
  hosts: all
  become: true
  roles:
    - users
    - common

- name: Configure dns
  hosts: dns
  become: true
  tags: dns
  roles:
    - dns

- name: Configure media
  hosts: media
  become: true
  tags: media
  roles:
    - media
    - docker

- name: Configure servers
  hosts: servers, !srv01.griend.dev
  become: true
  tags: servers
  roles:
    - kvm
    - terraform
