---
- name: Group dns 
  hosts: 
  - dns
  become: true
  roles:
  - common
  - dns
  tags: dns

- name: Group admin 
  hosts: 
  - admin
  become: true
  roles:
  - common
  - kvm
  - terraform
  - docker
  tags: admin

- name: Group gitlab 
  hosts: 
  - gitlab
  become: true
  roles:
  - common
  - docker
  - gitlab
  tags: gitlab
