---
- name: Group dns 
  hosts: 
  - all
  become: true
  roles:
  - common
  tags: common

- name: Group dns 
  hosts: 
  - dns
  become: true
  roles:
  - dns
  tags: dns

- name: Group gitlab 
  hosts: 
  - gitlab
  become: true
  roles:
  - docker
  - gitlab
  tags: github
