---
- name: Install packages
  ansible.builtin.package:
    name: '{{ common_packages }}'
    state: present

- name: Edit /etc/default/console-setup CODESET
  ansible.builtin.lineinfile:
    path: /etc/default/console-setup
    regexp: '^CODESET='
    line: 'CODESET="Lat15"'
  when: ansible_virtualization_role == 'host'

- name: Edit /etc/default/console-setup FONTFACE
  ansible.builtin.lineinfile:
    path: /etc/default/console-setup
    regexp: '^FONTFACE='
    line: 'FONTFACE="Terminus"'
  when: ansible_virtualization_role == 'host'

- name: Edit /etc/default/console-setup FONTSIZE
  ansible.builtin.lineinfile:
    path: /etc/default/console-setup
    regexp: '^FONTSIZE='
    line: 'FONTSIZE="16x32"'
  when: ansible_virtualization_role == 'host'

- name: Generate locale
  ansible.builtin.locale_gen:
    name: '{{ common_locale }}'
    state: present

- name: Get current locale
  ansible.builtin.command: localectl status
  register: locale_status
  changed_when: false

- name: Parse 'LANG' from current locale
  ansible.builtin.set_fact:
    locale_lang: "{{ locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | first }}"

- name: Set default locale
  ansible.builtin.command: localectl set-locale "{{ common_locale }}"
  changed_when: locale_lang != common_locale

- name: Create /etc/sudoers.d/adm
  ansible.builtin.copy:
    src: sudo.adm
    dest: /etc/sudoers.d/adm
    owner: root
    group: root
    mode: "0644"

- name: Create /etc/sudoers.d/ansible
  ansible.builtin.copy:
    src: sudo.ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: "0644"

- name: Set timezone
  community.general.timezone:
    name: '{{ common_timezone }}'
    hwclock: UTC
