---
- hosts: all
  become: true
  serial: 1
  
  tasks:
  - name: Update and upgrade apt packages
    ansible.builtin.apt:
      upgrade: full
      update_cache: yes
      autoremove: yes
      autoclean: yes
  
  - name: Check if reboot is required
    stat:
      path: /var/run/reboot-required
    register: reboot_required_check

  - name: Reboot if kernel updated
    reboot:
      msg: "Reboot initiated by Ansible for kernel updates"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
    when: reboot_required_check.stat.exists

