---
- hosts: all
  become: true
  serial: 1
  
  tasks:
  - name: Update and upgrade apt packages
    ansible.builtin.apt:
      upgrade: full
      update_cache: yes
      autoremove: yes
      autoclean: yes
